# https://github.com/marketplace/actions/electronegativity
name: Security analysis
on: [push, pull_request]

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Installing dependencies
      run: yarn
    - name: Building UI
      run: |
        yarn build:tasks
        yarn build:webpack
    - uses: doyensec/electronegativity-action@v1.1
    - uses: github/codeql-action/upload-sarif@v1
